spring:
  application:
    name : demo-project
  profiles :
    active : dev
  security :
    user :
      name : user
      password : password
  datasource:
    driver-class-name : org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#  jpa :
#    database-platform : org.hibernate.dialect.PostgreSQL9Dialect
#    hibernate :
#      dialect : org.hibernate.dialect.PostgreSQLDialect

server :
  port : 8080
  servlet :
    context-path : /api/v1
